import { Project } from './project.model'

export const PROJECTS: Project[] = [

  // ===== TIER 1: Ingeniería / Full Stack propio (lo más fuerte) =====

  {
    id: 17,
    category: 'professional-client',
    image: '/assets/projects/tolaria/tolaria1.webp',
    images: ['/assets/projects/tolaria/tolaria1.webp', '/assets/projects/tolaria/tolaria2.webp', '/assets/projects/tolaria/tolaria3.webp', '/assets/projects/tolaria/tolaria4.webp', '/assets/projects/tolaria/tolaria5.webp', '/assets/projects/tolaria/tolaria6.webp', '/assets/projects/tolaria/tolaria7.webp', '/assets/projects/tolaria/tolaria8.webp', '/assets/projects/tolaria/tolaria9.webp'],
    title: 'Tolaria - Trading Card Marketplace',
    technologies: ['WordPress', 'WooCommerce', 'PHP', 'JavaScript', 'Divi'],
    simpleDescription: 'Multi-vendor marketplace for Magic: The Gathering and Pokemon trading cards.',
    description: 'I owned the delivery of Tolaria from an empty theme to an operational e-commerce platform. I structured the site with Divi, built category and attribute-based product discovery, created reusable product layouts, and implemented seller and administrator workflows, product moderation, registration, and login with custom PHP. I also integrated the Onvopay payment gateway, developed an AJAX cart, and optimized key graphics by moving them to SVG.',
    problem: 'I needed to turn an empty theme into an operational marketplace for Magic: The Gathering and Pokemon trading cards. The project required clear product discovery as well as workflows for sellers and administrators.',
    solution: 'I structured the marketplace around category and attribute-based discovery, reusable product layouts, and separate seller and administrator workflows. I also implemented moderation, registration, login, payments, and an AJAX cart to support the complete purchasing flow.',
    result: 'The site became an operational marketplace where shoppers can discover cards, sellers can participate, and administrators can manage products and marketplace activity.',
    liveUrl: 'https://tolariacr.com/',
    clientName: 'Tolaria'
  },
  {
    id: 16,
    category: 'personal',
    image: '/assets/projects/securesight/ss1.webp',
    images: [
      '/assets/projects/securesight/ss1.webp',
      '/assets/projects/securesight/ss2.webp',
      '/assets/projects/securesight/ss3.webp',
    ],
    title: 'SecureSight',
    technologies: ['Angular', 'Python', 'FastAPI', 'Security'],
    simpleDescription: 'A comprehensive security monitoring and surveillance platform for real-time threat detection and analysis.',
    description: 'SecureSight is a modern security monitoring application designed to provide real-time visibility and control over your infrastructure. Built with Angular and TypeScript for the frontend, and Python with FastAPI for the backend, it offers advanced features for threat detection, system monitoring, and security analytics. The platform enables users to track security events, analyze patterns, and respond quickly to potential threats.',
    problem: 'I wanted to explore how a security monitoring workflow could turn infrastructure activity into information that is easier to inspect and act on. The challenge was to make threat detection and event analysis understandable in one place.',
    solution: 'I built a monitoring platform that brings security events, infrastructure visibility, pattern analysis, and response-oriented workflows together. I organized the experience around tracking events and surfacing the signals users need to investigate instead of presenting disconnected information.',
    result: 'Users can review security events, analyze patterns, and respond to potential threats from a single interface.',
    githubUrl: 'https://github.com/AlonsoJIC/SecureSight'
  },
  {
    id: 19,
    category: 'professional-client',
    image: '/assets/projects/camara-industrias/camara1.webp',
    images: ['/assets/projects/camara-industrias/camara1.webp', '/assets/projects/camara-industrias/camara2.webp', '/assets/projects/camara-industrias/camara3.webp', '/assets/projects/camara-industrias/camara4.webp'],
    title: 'Camara de Industrias de Costa Rica - Data Migration',
    technologies: ['Web Scraping', 'WordPress', 'CSV', 'Divi'],
    simpleDescription: 'Automated migration of 707 association member records and large-scale content publishing.',
    description: 'I replaced a planned manual data-entry process with an extraction pipeline that scraped the source data, generated a clean CSV, and bulk-imported 707 association records. I also published and formatted 550 forum posts with WebP-optimized imagery, reducing repetitive work and the risk of transcription errors.',
    problem: 'The planned manual process for migrating association records and forum content would have required repetitive data entry. The project needed a more reliable way to move the existing information into the new site.',
    solution: 'I built an extraction and transformation workflow that scraped the source data, generated a clean CSV, and bulk-imported the association records. I also published and formatted the forum content with optimized imagery so the migration covered both structured records and editorial material.',
    result: 'The client received migrated association records and forum content through a repeatable workflow that reduced manual transcription work.',
    clientName: 'Camara de Industrias de Costa Rica'
  },
  {
    id: 15,
    category: 'personal',
    image: '/assets/projects/tracked/tcd0.webp',
    images: [
      '/assets/projects/tracked/tcd1.webp',
      '/assets/projects/tracked/tcd2.webp',
      '/assets/projects/tracked/tcd3.webp',
    ],
    title: 'Tracked',
    technologies: ['Angular', 'Supabase'],
    simpleDescription: 'Application for tracking IPs, domains, agents, countries, and more in real-time. All from the persons that visit your website.',
    description: 'This project is a web application that allows users to track various data points such as IP addresses, domains, user agents, countries, and more in real-time. It is designed to help website owners monitor and analyze the traffic visiting their sites. The application is built using Angular for the frontend and Supabase for the backend, providing a seamless and efficient user experience. Also you could try the demo https://tracked2026.vercel.app/',
    problem: 'I wanted to make the information generated by website visitors easier to inspect in one place. The challenge was to turn scattered visitor data into a usable monitoring workflow.',
    solution: 'I built a dashboard that organizes visitor activity around IP addresses, domains, user agents, countries, and related data points. I focused the experience on near real-time visibility so website owners can inspect traffic as it arrives.',
    result: 'Website owners can review visitor information from a single interface and monitor incoming traffic with more context.',
    githubUrl: 'https://github.com/AlonsoJIC/Tracked'
  },
  {
    id: 7,
    category: 'personal',
    image: '/assets/projects/workflow/P2-1.webp',
    images: [
      '/assets/projects/workflow/P2-1.webp',
      '/assets/projects/workflow/P2-2.webp',
      '/assets/projects/workflow/P2-3.webp',
      '/assets/projects/workflow/P2-4.webp',
      '/assets/projects/workflow/P2-5.webp',
    ],
    title: 'Workflow',
    technologies: ['Angular', 'TypeScript', 'Spring Boot'],
    simpleDescription: 'A project management application for team collaboration and task tracking.',
    description: 'Workflow is a project management application designed to help teams collaborate and manage their tasks efficiently. It offers features such as task assignment, progress tracking, and deadline management to streamline workflows and enhance productivity.',
    problem: 'I wanted to model the everyday coordination problems that teams face when assigning work, tracking progress, and managing deadlines. The project gave me a way to practice a complete workflow rather than an isolated CRUD screen.',
    solution: 'I built a project management application around task assignment, progress tracking, and deadline management. I organized the experience so team work can be viewed as an ongoing flow from assignment through completion.',
    result: 'Teams can use a shared workspace to assign tasks, follow their progress, and keep deadlines visible.',
    githubUrl: 'https://github.com/AlonsoJIC/WorkFlow'
  },

  {
    id: 8,
    category: 'personal',
    image: '/assets/projects/employee-management-system/P3-1.webp',
    images: [
      '/assets/projects/employee-management-system/P3-1.webp',
      '/assets/projects/employee-management-system/P3-2.webp',
      '/assets/projects/employee-management-system/P3-3.webp',
      '/assets/projects/employee-management-system/P3-4.webp',
      '/assets/projects/employee-management-system/P3-5.webp',
    ],
    title: 'Employee Management System',
    technologies: ['React', 'Laravel'],
    simpleDescription: 'A web application to manage employees, departments, and roles within a company.',
    description: 'The Employee Management System is a web application designed to streamline the management of employee information, departments, and roles within a company. Built with React for the frontend and Laravel for the backend, this system provides an intuitive interface for HR personnel to add, update, and view employee records efficiently.',
    problem: 'I wanted to practice an administrative workflow for keeping employee information, departments, and roles organized. The challenge was presenting those related records in a way that supports routine HR updates.',
    solution: 'I built an interface for HR personnel to add, update, and view employee records while keeping departments and roles part of the same management flow. I focused the experience on straightforward record handling instead of scattering related information across separate screens.',
    result: 'HR users can manage employee records, departments, and roles from a single web application.',
  },
  {
    id: 10,
    category: 'personal',
    image: '/assets/projects/not-found-404-library/lb0.webp',
    images: [
      '/assets/projects/not-found-404-library/lb0.webp',
      '/assets/projects/not-found-404-library/lb1.webp',
      '/assets/projects/not-found-404-library/lb2.webp',
      '/assets/projects/not-found-404-library/lb3.webp',
      '/assets/projects/not-found-404-library/lbdb.webp',
    ],
    title: 'Not Found 404 Library',
    technologies: ['Visual Studio 2022', 'C#', '.NET', 'SQL Server', 'ADO.NET'],
    simpleDescription: 'A desktop application for managing a library system with CRUD operations.',
    description: 'A desktop application for managing a library system. The application allows users to perform CRUD operations on books, authors, and users. It features a user-friendly interface built with Windows Forms and utilizes ADO.NET for database connectivity with SQL Server. Implemented search functionality to quickly locate books and authors within the library database.',
    problem: 'I wanted to practice building a desktop system around a structured library workflow. The challenge was managing books, authors, and users while making records easy to locate and maintain.',
    solution: 'I built a desktop application with CRUD workflows for books, authors, and users, plus search for quickly locating books and authors. I connected the interface to a relational database so the records could be stored and updated as part of one system.',
    result: 'Library staff can maintain core records and find books or authors without manually scanning the entire database.',
  },
  {
    id: 9,
    category: 'personal',
    image: '/assets/projects/todum/td1.webp',
    images: [
      '/assets/projects/todum/td1.webp',
      '/assets/projects/todum/td2.webp',
      '/assets/projects/todum/td3.webp',
      '/assets/projects/todum/td4.webp',
      '/assets/projects/todum/td5.webp',
    ],
    title: 'TODUM',
    technologies: ['Angular', 'TypeScript', 'Java', 'Spring Boot'],
    simpleDescription: 'A task management application with authentication and productivity features.',
    description: 'Created with Angular for the frontend and Spring Boot for the backend, this application features user authentication, task categorization, priority settings, and deadline reminders. The intuitive interface and robust functionality make it easy for users to manage their daily activities and improve productivity.',
    problem: 'I wanted to build a task manager that handled more than a simple list of items. The challenge was combining authentication with categories, priorities, and deadlines so users could organize daily work with more context.',
    solution: 'I built a task management workflow with authenticated access, categories, priority settings, and deadline reminders. I structured each task around the information users need to decide what to work on and when.',
    result: 'Users can organize daily activities by category and priority while keeping upcoming deadlines visible.',
    githubUrl: 'https://github.com/AlonsoJIC/TodumFront'
  },


  // ===== TIER 2: Trabajo de cliente con sustancia técnica =====

  {
    id: 21,
    category: 'professional-client',
    image: '/assets/projects/simtec/simtec1.webp',
    images: ['/assets/projects/simtec/simtec1.webp', '/assets/projects/simtec/simtec2.webp', '/assets/projects/simtec/simtec3.webp'],
    title: 'Simtec Equipo Medico - Functional Improvements',
    technologies: ['JavaScript', 'jQuery', 'WordPress', 'Divi'],
    simpleDescription: 'Custom contact-routing and navigation improvements for a medical equipment website.',
    description: 'I built a custom JavaScript and jQuery solution that split sales and technical-support inquiries through the existing contact widget, avoiding a paid plugin upgrade. I also replaced a broken Waze redirect with a Google Maps integration that opens the visitor navigation app, and standardized typography and imagery across the site.',
    problem: 'Simtec needed its existing contact widget to distinguish sales inquiries from technical-support requests without paying for a plugin upgrade. The site also had a broken map redirect and inconsistent visual details.',
    solution: 'I extended the existing contact interaction with custom routing for sales and support inquiries. I replaced the broken Waze redirect with a Google Maps flow that opens the visitor navigation app, then standardized typography and imagery across the site.',
    result: 'Visitors can route their inquiry more clearly and open directions through a working map integration without adding the paid plugin upgrade.',
    liveUrl: 'https://simteccr.com/',
    clientName: 'Simtec Equipo Medico'
  },
  {
    id: 18,
    category: 'professional-client',
    image: '/assets/projects/lago-sarmiento/lys1.webp',
    images: ['/assets/projects/lago-sarmiento/lys1.webp', '/assets/projects/lago-sarmiento/lys2.webp', '/assets/projects/lago-sarmiento/lys3.webp'],
    title: 'Lago & Sarmiento - Corporate Website',
    technologies: ['WordPress', 'ACF', 'PHP', 'Divi'],
    simpleDescription: 'Self-manageable corporate website with structured content architecture.',
    description: 'I led the end-to-end build of Lago & Sarmiento, translating the brand manual into a structured WordPress platform. I created custom post types and Advanced Custom Fields for courses, news, workshops, and resources, allowing the client to manage content independently. I also developed a custom events carousel and implemented the site visual identity, contact channels, maps, and institutional pages.',
    problem: 'Lago & Sarmiento needed a corporate website that followed its brand manual while allowing the client to manage structured content independently. The challenge was supporting several content types without making future updates depend on code changes.',
    solution: 'I translated the brand into a structured content platform with dedicated models for courses, news, workshops, and resources. I also built an events carousel and organized the visual identity, contact channels, maps, and institutional information into one maintainable experience.',
    result: 'The client received a self-manageable corporate website with structured content areas for ongoing updates.',
    clientName: 'Lago & Sarmiento'
  },
  {
    id: 24,
    category: 'professional-client',
    image: '/assets/projects/sibowak/sibowak1.webp',
    images: ['/assets/projects/sibowak/sibowak1.webp', '/assets/projects/sibowak/sibowak2.webp', '/assets/projects/sibowak/sibowak3.webp'],
    title: 'SIBOWAK - Institutional Website',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Foundational architecture and global design system for an institutional website.',
    description: 'I built the foundational architecture for SIBOWAK across six business areas: organization, wellness, culture, home, products, and business. I also established the base template and global Divi style system used by later build phases.',
    problem: 'SIBOWAK needed one institutional foundation that could support six different business areas without each section feeling disconnected. The project required a reusable visual and structural base for later phases.',
    solution: 'I organized the site architecture across organization, wellness, culture, home, products, and business. I also established the base template and global style system so later sections could be built from consistent rules.',
    result: 'The project delivered a reusable foundation that gave the six business areas a shared structure and visual system.',
    liveUrl: 'https://sibowak.cr/',
    clientName: 'SIBOWAK'
  },
  {
    id: 36,
    category: 'professional-client',
    image: '/assets/projects/goltech/goltech1.webp',
    images: ['/assets/projects/goltech/goltech1.webp', '/assets/projects/goltech/goltech2.webp', '/assets/projects/goltech/goltech3.webp', '/assets/projects/goltech/goltech4.webp', '/assets/projects/goltech/goltech5.webp'],
    title: 'Goltech - Scientific Equipment Store',
    technologies: ['WordPress', 'WooCommerce', 'PHP', 'Divi'],
    simpleDescription: 'B2B catalog and e-commerce website for scientific, medical, laboratory, and industrial equipment.',
    description: 'I developed the digital presence for Goltech, a Costa Rican company that supplies precision scientific equipment to laboratories, industries, and medical centers. The site organizes product divisions, catalog discovery, technical guidance, logistics, and post-sale support into a complete commercial experience.',
    problem: 'Goltech needed a digital catalog that could present a broad range of scientific, medical, laboratory, and industrial equipment while helping businesses find the right solution. The site also needed to communicate the company\'s technical guidance, logistics, installation, and post-sale support.',
    solution: 'I structured the website around product divisions, category-based discovery, featured products, and direct paths to advice or quotations. I also organized the commercial content around the full service journey, from equipment selection and import logistics to installation and technical support.',
    result: 'Businesses can explore Goltech\'s equipment catalog, identify relevant product categories, and contact specialists for advice or a quotation.',
    liveUrl: 'https://darkgray-squid-755461.hostingersite.com/',
    clientName: 'Goltech'
  },
  {
    id: 31,
    category: 'professional-client',
    image: '/assets/projects/vv-phoenix-ops/vvphoenix1.webp',
    images: ['/assets/projects/vv-phoenix-ops/vvphoenix1.webp', '/assets/projects/vv-phoenix-ops/vvphoenix2.webp', '/assets/projects/vv-phoenix-ops/vvphoenix3.webp'],
    title: 'VV Phoenix Ops',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Full corporate website for a project management staffing and delivery support company.',
    description: 'I built the complete corporate website for VV Phoenix Ops, creating a conversion-focused brand narrative around project staffing, PMO support, implementation leadership, and nearshore operations. The site includes service positioning, trust-building sections, contact flow, and a clean structure designed to communicate expertise and drive qualified consultations.',
    problem: 'VV Phoenix Ops needed a corporate website that could explain several project delivery and staffing services while building trust with prospective clients. The challenge was turning a broad offer into a clear path toward consultation.',
    solution: 'I built the site around a focused narrative for project staffing, PMO support, implementation leadership, and nearshore operations. I organized service positioning, trust-building content, and the contact flow into one structure aimed at qualified consultations.',
    result: 'The company received a complete digital presence that explains its offer and gives prospective clients a clear way to start a conversation.',
    liveUrl: 'https://vvphoenixops.com/',
    clientName: 'VV Phoenix Ops'
  },
  {
    id: 34,
    category: 'professional-client',
    image: '/assets/projects/systec/systec1.webp',
    images: ['/assets/projects/systec/systec1.webp', '/assets/projects/systec/systec2.webp', '/assets/projects/systec/systec3.webp', '/assets/projects/systec/systec4.webp'],
    title: 'SYSTEC',
    technologies: ['WordPress', 'CSS', 'JavaScript', 'IT Services'],
    simpleDescription: 'Complete digital presence for an IT infrastructure and cybersecurity company serving SMEs.',
    description: 'I developed the complete website for SYSTEC in close collaboration with the client to reflect their infrastructure, IT support, and cybersecurity services. The project included a full corporate presentation, service storytelling, credibility elements, and a communication structure designed for lead generation and trust-building with business clients.',
    problem: 'SYSTEC needed a complete digital presence that could explain infrastructure, IT support, and cybersecurity services to small and medium-sized businesses. The site also needed to build enough trust for visitors to start a business conversation.',
    solution: 'I developed the corporate presentation around service storytelling, credibility elements, and a clear communication structure. I worked closely with the client to make the website reflect the company offer while keeping lead generation visible throughout the experience.',
    result: 'SYSTEC received a complete website that presents its services and gives business clients a clearer path to contact.',
    liveUrl: 'https://systec.cr/',
    clientName: 'SYSTEC'
  },
  {
    id: 32,
    category: 'professional-client',
    image: '/assets/projects/estrategika/estrategika1.webp',
    images: ['/assets/projects/estrategika/estrategika1.webp', '/assets/projects/estrategika/estrategika2.webp', '/assets/projects/estrategika/estrategika3.webp'],
    title: 'Estrategika',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Full business consulting website focused on management, growth, and operational structure.',
    description: 'I designed and developed the complete website for Estrategika, translating the consulting model into a clear and persuasive digital presence. The project covers the company positioning, service offer, methodology, credibility-building content, and calls to action aimed at business owners who need better governance, accountability, and execution.',
    problem: 'Estrategika needed to translate a consulting model focused on governance, accountability, and execution into a digital presence that business owners could understand quickly. The site had to connect the service offer with a credible path to action.',
    solution: 'I designed the website around the company positioning, service offer, methodology, and credibility-building content. I connected those sections with calls to action so the narrative could move visitors from understanding the offer toward contact.',
    result: 'The consulting business received a complete website that presents its model, services, and next steps in a more coherent flow.',
    clientName: 'Estrategika'
  },
  {
    id: 33,
    category: 'professional-client',
    image: '/assets/projects/sm-consultora/smconsultora1.webp',
    images: ['/assets/projects/sm-consultora/smconsultora1.webp', '/assets/projects/sm-consultora/smconsultora2.webp', '/assets/projects/sm-consultora/smconsultora3.webp'],
    title: 'SM Consultora',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Strategic consulting website centered on public procurement readiness and business growth.',
    description: 'I created the full website for SM Consultora, building a strong narrative around planning, financial structure, organizational readiness, and public bidding strategy. The site consolidates the service offer, value proposition, corporate positioning, and contact experience to help companies compete with more clarity and strength.',
    problem: 'SM Consultora needed a website that could explain its work across planning, financial structure, organizational readiness, and public bidding strategy. The challenge was consolidating those services into a clear value proposition for companies.',
    solution: 'I built the narrative around the consulting offer, corporate positioning, and the steps that support readiness for public procurement. I connected the service content with a focused contact experience so the site could guide interested companies toward a conversation.',
    result: 'The company received a structured digital presence that makes its consulting offer and contact path easier to understand.',
    clientName: 'SM Consultora'
  },
  {
    id: 12,
    category: 'professional-client',
    image: '/assets/projects/quantum-games/qg1.webp',
    images: [
      '/assets/projects/quantum-games/qg1.webp',
    ],
    title: 'Quantum Games',
    technologies: ['Angular', 'TypeScript', 'HTML', 'SCSS'],
    simpleDescription: 'A gaming company website with an admin panel for content management.',
    description: 'Quantum Games is a web application created for a friend who wants to start a gaming company. This web was created with Angular, TypeScript, HTML, and SCSS. JWT authentication was implemented for the admin panel, where he can manage the games and the content of the website.',
    problem: 'A friend starting a gaming company needed a public website that could present the business while allowing its content to be maintained over time. The challenge was to give the admin area controlled access without making content updates part of the public experience.',
    solution: 'I built the public gaming company website together with an authenticated admin panel for managing games and site content. I separated content management from the visitor-facing experience so the site could evolve without rebuilding its public pages manually.',
    result: 'The project provides a public gaming website and a protected workflow for updating its games and content.',
  },
  {
    id: 13,
    category: 'professional-client',
    image: '/assets/projects/joyarte/ja1.webp',
    images: [
      '/assets/projects/joyarte/ja1.webp',
      '/assets/projects/joyarte/ja2.webp',
      '/assets/projects/joyarte/ja3.webp',
    ],
    title: 'Joyarte',
    technologies: ['Angular', 'TypeScript', 'HTML', 'SCSS'],
    simpleDescription: 'A modern website for a local art gallery showcasing artworks and exhibitions.',
    description: 'Joyarte is a website created for a local art gallery in my city. This web was created with Angular, TypeScript, HTML, and SCSS, featuring a clean design to showcase artworks.',
    problem: 'A local art gallery needed a digital space where visitors could discover its artworks and exhibitions. The challenge was to make the gallery content the focus while keeping the presentation clean and easy to browse.',
    solution: 'I built a gallery website with a clean visual structure that gives the artwork room to lead the experience. I organized the presentation around the gallery\'s content instead of adding unnecessary interface complexity.',
    result: 'Joyarte received a focused online showcase for presenting its artworks and exhibitions to visitors.',
    githubUrl: 'https://github.com/AlonsoJIC/JoyarteWeb'
  },
  {
    id: 37,
    category: 'professional-client',
    image: '/assets/projects/abrazo-de-esperanza/abrazo1.webp',
    images: ['/assets/projects/abrazo-de-esperanza/abrazo1.webp', '/assets/projects/abrazo-de-esperanza/abrazo2.webp', '/assets/projects/abrazo-de-esperanza/abrazo3.webp'],
    title: 'Fundación Abrazo de Esperanza',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Institutional website for a foundation supporting families with babies in neonatal intensive care.',
    description: 'I created the institutional website for Fundación Abrazo de Esperanza, a Costa Rican organization that supports families whose children are hospitalized in the neonatal intensive care unit at Hospital San Vicente de Paúl. The site explains the foundation\'s purpose and gives visitors clear ways to donate, volunteer, or get in touch.',
    problem: 'Fundación Abrazo de Esperanza needed a clear and compassionate digital presence to explain how it supports families during neonatal hospitalization. The site also needed to connect visitors with concrete ways to contribute through donations, volunteering, and direct contact.',
    solution: 'I built the website around the foundation\'s purpose, its three support pillars, and the vision of creating a dignified space for families. I organized the content around clear calls to action so visitors can understand the mission and choose how they want to help.',
    result: 'Families, volunteers, and donors can understand the foundation\'s work and find a direct path to participate or request more information.',
    liveUrl: 'https://lightgoldenrodyellow-seal-708862.hostingersite.com/',
    clientName: 'Fundación Abrazo de Esperanza'
  },
  {
    id: 20,
    category: 'professional-client',
    image: '/assets/projects/salud-en-linea/salud1.webp',
    images: ['/assets/projects/salud-en-linea/salud1.webp', '/assets/projects/salud-en-linea/salud2.webp'],
    title: 'Salud en Linea - E-commerce Maintenance',
    technologies: ['WordPress', 'WooCommerce', 'Divi'],
    simpleDescription: 'Content, product catalog, theme-template fixes, and platform maintenance for an online store.',
    description: 'I worked across editorial content, catalog architecture, and platform reliability for Salud en Linea. I rebuilt the product taxonomy, republished the inventory, fixed a Divi Theme Builder conflict, and completed backups, WordPress and plugin updates, dependency-conflict resolution, and security hardening.',
    problem: 'Salud en Linea needed its online store content and product catalog brought back into a consistent structure, while platform conflicts and maintenance issues affected reliability. The work also required attention to backups and security.',
    solution: 'I rebuilt the product taxonomy, republished the inventory, and fixed the Divi Theme Builder conflict affecting the site. I combined those content changes with updates, dependency resolution, backups, and security hardening as one maintenance workflow.',
    result: 'The store ended with a cleaner catalog structure and a more stable, maintained platform for ongoing e-commerce work.',
    liveUrl: 'https://saludenlineacr.shop/',
    clientName: 'Salud en Linea'
  },

  // ===== TIER 3: Práctica de frontend personal =====
  {
    id: 1,
    category: 'personal',
    image: '/assets/projects/colors-generator/cg1.webp',
    images: [
      '/assets/projects/colors-generator/cg1.webp',
      '/assets/projects/colors-generator/cg2.webp',
      '/assets/projects/colors-generator/cg3.webp',
      '/assets/projects/colors-generator/cg4.webp',
      '/assets/projects/colors-generator/cg5.webp',
    ],
    title: 'Colors Generator',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    simpleDescription: 'A web application gradient generator with multiple customization options.',
    description: 'It has many features such as adding or removing colors, choosing color directions, generating random colors and choosing default color palette. This application was created with HTML, CSS, JavaScript and Bootstrap.',
    problem: 'I wanted to practice building an interactive visual tool where users could experiment with gradients instead of defining colors manually. The main challenge was keeping multiple customization options easy to understand.',
    solution: 'I built a generator that lets users add or remove colors, change the gradient direction, create random combinations, and choose from default palettes. I kept the controls close to the live preview so each change is immediately visible.',
    result: 'Users can create and adjust custom gradients interactively and use the generated result as a starting point for their designs.',
    githubUrl: 'https://github.com/AlonsoJIC/colors-generator'
  },
  {
    id: 6,
    category: 'personal',
    image: '/assets/projects/little-games/lg5.webp',
    images: [
      '/assets/projects/little-games/lg1.webp',
      '/assets/projects/little-games/lg2.webp',
      '/assets/projects/little-games/lg3.webp',
      '/assets/projects/little-games/lg4.webp',
      '/assets/projects/little-games/lg5.webp',
    ],
    title: 'Little Games',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    simpleDescription: 'A collection of simple browser games built with vanilla JavaScript.',
    description: 'Little Games is a web app featuring simple games created with native JavaScript, HTML, and CSS. The app includes 4 games: XO Game, Flip the Cards, Guess the Number, and Mines Game.',
    problem: 'I wanted to practice browser interaction and game logic without relying on a framework. The challenge was to bring several small games together while keeping each one understandable and playable.',
    solution: 'I built a collection containing XO Game, Flip the Cards, Guess the Number, and Mines Game. Each game uses direct browser interactions and its own rules while sharing a single accessible entry point.',
    result: 'Users can open one web app and play four different browser games built with native front-end behavior.',
    githubUrl: 'https://github.com/AlonsoJIC/LittleGames'
  },
  {
    id: 2,
    category: 'personal',
    image: '/assets/projects/trello-clone/tre1.webp',
    images: [
      '/assets/projects/trello-clone/tre1.webp',
      '/assets/projects/trello-clone/tre2.webp',
      '/assets/projects/trello-clone/tre3.webp',
      '/assets/projects/trello-clone/tre4.webp',
      '/assets/projects/trello-clone/tre5.webp',
    ],
    title: 'Trello Clone - Project Manager',
    technologies: ['Angular', 'Tailwind CSS', 'JWT'],
    simpleDescription: 'A Trello-inspired project management application with authentication and drag-and-drop features.',
    description: 'Trello is a project management software similar to a ToDo application but with advanced features. In this clone, I implemented authentication, registration, password recovery, token management, To Do/Doing/Done boards, drag-and-drop transfers, and item creation.',
    problem: 'I wanted to go beyond a basic to-do list and practice the architecture of a collaborative project management workflow. The challenge was coordinating authenticated users with board state and drag-and-drop task movement.',
    solution: 'I built a Trello-inspired workspace with registration, password recovery, token management, and To Do, Doing, and Done boards. I centered the interaction around creating items and moving them between states so task progress stays visible.',
    result: 'Users can sign in, create tasks, and move them through a visual workflow from one board state to another.',
    githubUrl: 'https://github.com/AlonsoJIC/Trello-clon'
  },
  {
    id: 5,
    category: 'personal',
    image: '/assets/projects/tesla-landing-page/Tesla1.webp',
    images: [
      '/assets/projects/tesla-landing-page/Tesla1.webp',
      '/assets/projects/tesla-landing-page/Tesla2.webp',
      '/assets/projects/tesla-landing-page/Tesla3.webp',
      '/assets/projects/tesla-landing-page/Tesla4.webp',
    ],
    title: 'Tesla Landing Page Clone',
    technologies: ['Astro', 'Tailwind CSS'],
    simpleDescription: 'A pixel-perfect clone of the Tesla website built with modern technologies.',
    description: 'A clone of the landing page of the famous electric cars company Tesla, created with Astro and Tailwind CSS for optimal performance and responsive design.',
    problem: 'I wanted to study how a polished automotive landing page uses visual hierarchy, responsive composition, and focused product sections. The challenge was reproducing that experience as a front-end practice project.',
    solution: 'I recreated the landing page structure with product-focused sections, responsive layouts, and the visual rhythm of the reference site. I kept the implementation centered on fast page delivery and consistent behavior across screen sizes.',
    result: 'The project demonstrates a responsive recreation of a product-oriented landing page with a clear visual hierarchy.',
    githubUrl: 'https://github.com/AlonsoJIC/landing_de_tesla_con_astro'
  },
  // ===== TIER 4: Mantenimiento / rediseño visual sin lógica de negocio propia =====

  {
    id: 22,
    category: 'professional-client',
    image: '/assets/projects/escojisa/escojisa1.webp',
    images: ['/assets/projects/escojisa/escojisa1.webp', '/assets/projects/escojisa/escojisa2.webp', '/assets/projects/escojisa/escojisa3.webp'],
    title: 'Escojisa CR - Site Redesign',
    technologies: ['WordPress', 'CSS', 'HTML', 'Divi'],
    simpleDescription: 'Responsive redesign and visual standardization based on iterative client reviews.',
    description: 'I drove a multi-round redesign of Escojisa CR, improving typography, color contrast, responsive layouts, footer structure, buttons, social integrations, and project imagery. I also migrated key icons to SVG and translated live client feedback into shipped visual and content updates.',
    problem: 'Escojisa CR needed a more consistent responsive presentation across its typography, contrast, layouts, navigation elements, and project imagery. The redesign also had to absorb repeated client feedback as the work evolved.',
    solution: 'I iterated through the visual system, adjusting layouts, buttons, footer structure, social integrations, and project presentation. I translated review feedback into shipped content and interface updates and moved key icons to SVG for a cleaner result.',
    result: 'The site received a more consistent responsive experience shaped through multiple rounds of client review.',
    liveUrl: 'https://escojisacr.com/',
    clientName: 'Escojisa CR'
  },
  {
    id: 25,
    category: 'professional-client',
    image: '/assets/projects/esfera-latam/esfera1.webp',
    images: ['/assets/projects/esfera-latam/esfera1.webp', '/assets/projects/esfera-latam/esfera2.webp', '/assets/projects/esfera-latam/esfera3.webp', '/assets/projects/esfera-latam/esfera4.webp'],
    title: 'Esfera Latam - UX and Visual Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Homepage redesign focused on content flow, calls to action, and visual consistency.',
    description: 'I led an ongoing UX and visual redesign of Esfera Latam\'s homepage, restructuring content for readability, adding calls to action, standardizing information cards, and aligning the palette, typography, and graphic components with the brand guidelines.',
    problem: 'Esfera Latam needed its homepage to communicate information more clearly and guide visitors through the offer with stronger calls to action. The visual system also needed to align more consistently with the brand guidelines.',
    solution: 'I restructured the homepage content flow, added calls to action, and standardized the information cards. I aligned the palette, typography, and graphic components so the page could communicate with a more consistent visual language.',
    result: 'The homepage gained a clearer content hierarchy, stronger action points, and a more consistent relationship with the brand.',
    liveUrl: 'https://esferalatam.com/',
    clientName: 'Esfera Latam'
  },
  {
    id: 26,
    category: 'professional-client',
    image: '/assets/projects/girasol-gatuno/girasol1.webp',
    images: ['/assets/projects/girasol-gatuno/girasol1.webp', '/assets/projects/girasol-gatuno/girasol2.webp', '/assets/projects/girasol-gatuno/girasol3.webp'],
    title: 'Girasol Gatuno - Visual Identity Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Responsive visual refresh with updated typography, imagery, navigation, and graphic components.',
    description: 'I led a visual identity refresh for Girasol Gatuno, reworking global typography, imagery, buttons, navigation links, CSS effects, and graphic components. I finished with responsive QA across mobile and desktop layouts.',
    problem: 'Girasol Gatuno needed its visual identity and interface details brought into a more consistent responsive system. The refresh covered typography, imagery, navigation, buttons, and the graphic components used across the site.',
    solution: 'I reworked the global visual elements and CSS effects, then checked the result across mobile and desktop layouts. I treated typography, imagery, navigation, and controls as one coordinated system instead of isolated fixes.',
    result: 'The site received a responsive visual refresh with more consistent presentation across its core interface elements.',
    liveUrl: 'https://girasolgatuno.com/',
    clientName: 'Girasol Gatuno'
  },
  {
    id: 27,
    category: 'professional-client',
    image: '/assets/projects/ecole-travel/ecole1.webp',
    images: ['/assets/projects/ecole-travel/ecole1.webp', '/assets/projects/ecole-travel/ecole2.webp', '/assets/projects/ecole-travel/ecole3.webp'],
    title: 'Ecole Travel - Content and Site Maintenance',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Ongoing blog and homepage maintenance with responsive content improvements.',
    description: 'I managed content and design updates for Ecole Travel, including author attribution, Instagram integration, homepage hero copy and imagery, and logo upscaling for sharper high-density display. I verified the changes through responsive QA.',
    problem: 'Ecole Travel needed ongoing content and homepage updates while preserving a reliable presentation across screen sizes. The work also included improving attribution, social integration, hero content, and image sharpness.',
    solution: 'I updated author attribution, integrated Instagram content, refined the homepage hero copy and imagery, and upscaled the logo for high-density displays. I verified the changes through responsive checks instead of treating the work as desktop-only maintenance.',
    result: 'The site received clearer editorial and homepage content with sharper branding and verified responsive behavior.',
    liveUrl: 'https://ecoletravel.com/',
    clientName: 'Ecole Travel'
  },
  {
    id: 29,
    category: 'professional-client',
    image: '/assets/projects/mundogluck/mundogluck1.webp',
    images: ['/assets/projects/mundogluck/mundogluck1.webp', '/assets/projects/mundogluck/mundogluck2.webp'],
    title: 'MundoGluck - About Us Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Responsive redesign of an About Us section through two rounds of client feedback.',
    description: 'I replaced an outdated carousel layout with a cleaner responsive template, refined copy and visual hierarchy through client feedback, and improved spacing, alignment, and social-media placement.',
    problem: 'MundoGluck needed its About Us section to move beyond an outdated carousel and communicate the company more clearly on responsive screens. The result also needed to incorporate feedback across two review rounds.',
    solution: 'I replaced the carousel with a cleaner responsive template and refined the copy and visual hierarchy through client review. I also adjusted spacing, alignment, and social-media placement to support the new structure.',
    result: 'The About Us section became a clearer responsive presentation shaped by two rounds of client feedback.',
    liveUrl: 'https://mundogluck.com/',
    clientName: 'MundoGluck'
  },
  {
    id: 35,
    category: 'professional-client',
    image: '/assets/projects/constructora-dia/constructoradia1.webp',
    images: ['/assets/projects/constructora-dia/constructoradia1.webp', '/assets/projects/constructora-dia/constructoradia2.webp'],
    title: 'Constructora DIA S.A.',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Project portfolio and institutional website for a construction company in Costa Rica.',
    description: 'I developed the projects section and supported the content architecture for Constructora DIA S.A., shaping a construction-focused portfolio that showcases residential, institutional, and commercial developments. The work included building a structured project showcase, improving information hierarchy, and creating a cleaner presentation for the company’s built work and credibility.',
    problem: 'Constructora DIA S.A. needed a clearer way to present its residential, institutional, and commercial developments as evidence of its work. The project required a structured portfolio and stronger information hierarchy.',
    solution: 'I developed the projects section and supported the content architecture around a construction-focused portfolio. I organized the project presentation so the company\'s built work and credibility could be understood more clearly.',
    result: 'The company received a cleaner, structured showcase for presenting its completed developments and institutional credibility.',
    clientName: 'Constructora DIA S.A.'
  },
  {
    id: 23,
    category: 'professional-client',
    image: '/assets/projects/fundacion-piedad/piedad1.webp',
    images: ['/assets/projects/fundacion-piedad/piedad1.webp', '/assets/projects/fundacion-piedad/piedad2.webp', '/assets/projects/fundacion-piedad/piedad3.webp'],
    title: 'Fundacion Piedad - Institutional Website',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Institutional website foundation for a nonprofit organization.',
    description: 'I led the first build phase of the foundation website, using the client brief and competitive analysis to create the organization presentation, history, and affiliated-schools sections.',
    problem: 'Fundacion Piedad needed a first digital foundation for presenting the organization, its history, and its relationship with affiliated schools. The initial build had to turn the client brief and reference research into a coherent institutional structure.',
    solution: 'I used the client brief and competitive analysis to shape the first information architecture and built the organization presentation, history, and affiliated-schools sections. I kept the initial scope focused on establishing the core institutional narrative.',
    result: 'The foundation received the first structured version of its institutional website and its key presentation sections.',
    clientName: 'Fundacion Piedad'
  },
  {
    id: 28,
    category: 'professional-client',
    image: '/assets/projects/el-maestro-en-casa/maestroencasa1.webp',
    images: ['/assets/projects/el-maestro-en-casa/maestroencasa1.webp', '/assets/projects/el-maestro-en-casa/maestroencasa2.webp'],
    title: 'El Maestro en Casa - Academic Content Architecture',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Academic content audit and structure redesign for a distance-learning platform.',
    description: 'I audited and reorganized academic content, removed duplicated shared materials, designed a new structure for the 11th-grade Biology curriculum, and identified resource gaps for follow-up planning.',
    problem: 'El Maestro en Casa needed its academic content reviewed and reorganized so shared materials were not duplicated and curriculum gaps were visible. The project focused on making the distance-learning structure easier to maintain and continue.',
    solution: 'I audited the existing material, removed duplicated shared resources, and designed a new structure for the 11th-grade Biology curriculum. I also documented missing resources so future planning could address them directly.',
    result: 'The platform received a cleaner academic structure and a clearer list of resource gaps for follow-up work.',
    clientName: 'El Maestro en Casa'
  },
  {
    id: 30,
    category: 'professional-client',
    image: '/assets/projects/esteban-bogantes/estebanbogantes1.webp',
    images: ['/assets/projects/esteban-bogantes/estebanbogantes1.webp', '/assets/projects/esteban-bogantes/estebanbogantes2.webp', '/assets/projects/esteban-bogantes/estebanbogantes3.webp'],
    title: 'Esteban Bogantes - Content and Visual Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Informational-page redesign with updated content, imagery, and visual consistency.',
    description: 'I redesigned a key informational page by replacing imagery, rewriting headings and subheadings within the defined color palette, and adjusting graphic elements to match the rest of the site.',
    problem: 'Esteban Bogantes needed an informational page whose content and imagery matched the visual direction of the rest of the site. The work had to improve clarity without breaking the defined color palette.',
    solution: 'I replaced the imagery, rewrote the headings and subheadings, and adjusted the graphic elements within the existing palette. I used the surrounding site as the reference for spacing and visual consistency.',
    result: 'The page gained updated content and imagery with a presentation that fits the rest of the site more closely.',
    liveUrl: 'https://estebanbogantes.com/',
    clientName: 'Esteban Bogantes'
  },
  {
    id: 11,
    category: 'professional-client',
    image: '/assets/projects/godo-painting-rework/gpr1.webp',
    images: [
      '/assets/projects/godo-painting-rework/gpr1.webp',
      '/assets/projects/godo-painting-rework/gpr2.webp',
      '/assets/projects/godo-painting-rework/gpr3.webp',
    ],
    title: 'Godo Painting - Rework',
    technologies: ['WordPress'],
    simpleDescription: 'Complete redesign of Godo Painting website with improved UX and SEO.',
    description: 'Godo Painting is a company that provides painting services in Tampa, FL. In this project, I made a complete redesign of the website to improve the user experience and SEO positioning.',
    problem: 'Godo Painting needed its existing website to communicate its services more clearly and provide a stronger foundation for search visibility. The redesign had to address both the visitor experience and the site structure.',
    solution: 'I redesigned the website around clearer service presentation and a more consistent navigation experience. I also applied SEO-oriented improvements so the refreshed structure could better support the company\'s online positioning.',
    result: 'The company received a redesigned website with a clearer user experience and a stronger SEO foundation.',
  },
  {
    id: 3,
    category: 'professional-client',
    image: '/assets/projects/godo-painting/gp1.webp',
    images: [
      '/assets/projects/godo-painting/gp1.webp',
      '/assets/projects/godo-painting/gp2.webp',
      '/assets/projects/godo-painting/gp3.webp',
      '/assets/projects/godo-painting/gp4.webp',
    ],
    title: 'Godo Painting - Tampa, FL',
    technologies: ['WordPress'],
    simpleDescription: 'Professional website for a painting services company in Tampa, Florida.',
    description: 'Godo Painting is a company that provides painting services in Tampa, FL. I provided freelance services for web creation, hosting, and SEO optimizations.',
    problem: 'Godo Painting needed a professional online presence for its painting services in Tampa, Florida. The project also needed hosting and search-engine improvements as part of the delivery.',
    solution: 'I created and hosted the company website around its painting services, then applied SEO improvements to make the business information easier to find and understand. I kept the structure focused on presenting the company and its offering clearly.',
    result: 'Godo Painting received a live business website with hosting and an improved foundation for communicating its services online.',
  },
  {
    id: 4,
    category: 'professional-client',
    image: '/assets/projects/emprende-en-casa/emp1.webp',
    images: [
      '/assets/projects/emprende-en-casa/emp1.webp',
      '/assets/projects/emprende-en-casa/emp2.webp',
      '/assets/projects/emprende-en-casa/emp3.webp',
      '/assets/projects/emprende-en-casa/emp4.webp',
    ],
    title: 'Emprende en Casa - Landing Page',
    technologies: ['Angular', 'Bootstrap'],
    simpleDescription: 'A landing page designed for selling books and courses through digital advertising.',
    description: 'A landing page for a customer who wanted to sell his books and courses using Google/Facebook Ads campaigns.',
    problem: 'The client needed a focused destination for visitors arriving from Google and Facebook advertising campaigns. The page had to present books and courses clearly and guide interested visitors toward the offer.',
    solution: 'I built a dedicated landing page that organizes the offer around the client\'s books and courses instead of treating it like a general website. I shaped the content flow to support paid-traffic visitors who need to understand the offer quickly.',
    result: 'The client received a campaign-ready landing page for presenting and promoting books and courses through digital advertising.',
    githubUrl: 'https://github.com/AlonsoJIC/EmprendeDesdeCasa'
  }

]