import { Project } from './project.model'

export const PROJECTS: Project[] = [

  {
    id: 16,
    category: 'personal',
    image: '/assets/ss1.webp',
    images: [
      '/assets/ss1.webp',
      '/assets/ss2.webp',
      '/assets/ss3.webp',
    ],
    title: 'SecureSight',
    technologies: ['Angular', 'Python', 'FastAPI', 'Security'],
    simpleDescription: 'A comprehensive security monitoring and surveillance platform for real-time threat detection and analysis.',
    description: 'SecureSight is a modern security monitoring application designed to provide real-time visibility and control over your infrastructure. Built with Angular and TypeScript for the frontend, and Python with FastAPI for the backend, it offers advanced features for threat detection, system monitoring, and security analytics. The platform enables users to track security events, analyze patterns, and respond quickly to potential threats.',
    githubUrl: 'https://github.com/AlonsoJIC/SecureSight'
  },
  {
    id: 15,
    category: 'personal',
    image: '/assets/tcd0.webp',
    images: [
      '/assets/tcd1.webp',
      '/assets/tcd2.webp',
      '/assets/tcd3.webp',
    ],
    title: 'Tracked',
    technologies: ['Angular', 'Supabase'],
    simpleDescription: 'Application for tracking IPs, domains, agents, countries, and more in real-time. All from the persons that visit your website.',
    description: 'This project is a web application that allows users to track various data points such as IP addresses, domains, user agents, countries, and more in real-time. It is designed to help website owners monitor and analyze the traffic visiting their sites. The application is built using Angular for the frontend and Supabase for the backend, providing a seamless and efficient user experience. Also you could try the demo https://tracked2026.vercel.app/',
    githubUrl: 'https://github.com/AlonsoJIC/Tracked'
  },
  {
    id: 1,
    category: 'personal',
    image: '/assets/cg1.webp',
    images: [
      '/assets/cg1.webp',
      '/assets/cg2.webp',
      '/assets/cg3.webp',
      '/assets/cg4.webp',
      '/assets/cg5.webp',
    ],
    title: 'Colors Generator',
    technologies: ['HTML', 'CSS', 'JavaScript', 'Bootstrap'],
    simpleDescription: 'A web application gradient generator with multiple customization options.',
    description: 'It has many features such as adding or removing colors, choosing color directions, generating random colors and choosing default color palette. This application was created with HTML, CSS, JavaScript and Bootstrap.',
    githubUrl: 'https://github.com/AlonsoJIC/colors-generator'
  },
  {
    id: 2,
    category: 'personal',
    image: '/assets/tre1.webp',
    images: [
      '/assets/tre1.webp',
      '/assets/tre2.webp',
      '/assets/tre3.webp',
      '/assets/tre4.webp',
      '/assets/tre5.webp',
    ],
    title: 'Trello Clone - Project Manager',
    technologies: ['Angular', 'Tailwind CSS', 'JWT'],
    simpleDescription: 'A Trello-inspired project management application with authentication and drag-and-drop features.',
    description: 'Trello is a project management software similar to a ToDo application but with advanced features. In this clone, I implemented authentication, registration, password recovery, token management, To Do/Doing/Done boards, drag-and-drop transfers, and item creation.',
    githubUrl: 'https://github.com/AlonsoJIC/Trello-clon'
  },
  {
    id: 3,
    category: 'professional-client',
    image: '/assets/gp1.webp',
    images: [
      '/assets/gp1.webp',
      '/assets/gp2.webp',
      '/assets/gp3.webp',
      '/assets/gp4.webp',
    ],
    title: 'Godo Painting - Tampa, FL',
    technologies: ['WordPress'],
    simpleDescription: 'Professional website for a painting services company in Tampa, Florida.',
    description: 'Godo Painting is a company that provides painting services in Tampa, FL. I provided freelance services for web creation, hosting, and SEO optimizations.'
  },
  {
    id: 4,
    category: 'professional-client',
    image: '/assets/emp1.webp',
    images: [
      '/assets/emp1.webp',
      '/assets/emp2.webp',
      '/assets/emp3.webp',
      '/assets/emp4.webp',
    ],
    title: 'Emprende en Casa - Landing Page',
    technologies: ['Angular', 'Bootstrap'],
    simpleDescription: 'A landing page designed for selling books and courses through digital advertising.',
    description: 'A landing page for a customer who wanted to sell his books and courses using Google/Facebook Ads campaigns.',
    githubUrl: 'https://github.com/AlonsoJIC/EmprendeDesdeCasa'
  },
  {
    id: 5,
    category: 'personal',
    image: '/assets/Tesla1.webp',
    images: [
      '/assets/Tesla1.webp',
      '/assets/Tesla2.webp',
      '/assets/Tesla3.webp',
      '/assets/Tesla4.webp',
    ],
    title: 'Tesla Landing Page Clone',
    technologies: ['Astro', 'Tailwind CSS'],
    simpleDescription: 'A pixel-perfect clone of the Tesla website built with modern technologies.',
    description: 'A clone of the landing page of the famous electric cars company Tesla, created with Astro and Tailwind CSS for optimal performance and responsive design.',
    githubUrl: 'https://github.com/AlonsoJIC/landing_de_tesla_con_astro'
  },
  {
    id: 6,
    category: 'personal',
    image: '/assets/lg5.webp',
    images: [
      '/assets/lg1.webp',
      '/assets/lg2.webp',
      '/assets/lg3.webp',
      '/assets/lg4.webp',
      '/assets/lg5.webp',
    ],
    title: 'Little Games',
    technologies: ['HTML', 'CSS', 'JavaScript'],
    simpleDescription: 'A collection of simple browser games built with vanilla JavaScript.',
    description: 'Little Games is a web app featuring simple games created with native JavaScript, HTML, and CSS. The app includes 4 games: XO Game, Flip the Cards, Guess the Number, and Mines Game.',
    githubUrl: 'https://github.com/AlonsoJIC/LittleGames'
  },
  {
    id: 7,
    category: 'personal',
    image: '/assets/P2-1.webp',
    images: [
      '/assets/P2-1.webp',
      '/assets/P2-2.webp',
      '/assets/P2-3.webp',
      '/assets/P2-4.webp',
      '/assets/P2-5.webp',
    ],
    title: 'Workflow',
    technologies: ['Angular', 'TypeScript', 'Spring Boot'],
    simpleDescription: 'A project management application for team collaboration and task tracking.',
    description: 'Workflow is a project management application designed to help teams collaborate and manage their tasks efficiently. It offers features such as task assignment, progress tracking, and deadline management to streamline workflows and enhance productivity.',
    githubUrl: 'https://github.com/AlonsoJIC/WorkFlow'
  },
  {
    id: 8,
    category: 'personal',
    image: '/assets/P3-1.webp',
    images: [
      '/assets/P3-1.webp',
      '/assets/P3-2.webp',
      '/assets/P3-3.webp',
      '/assets/P3-4.webp',
      '/assets/P3-5.webp',
    ],
    title: 'Employee Management System',
    technologies: ['React', 'Laravel'],
    simpleDescription: 'A web application to manage employees, departments, and roles within a company.',
    description: 'The Employee Management System is a web application designed to streamline the management of employee information, departments, and roles within a company. Built with React for the frontend and Laravel for the backend, this system provides an intuitive interface for HR personnel to add, update, and view employee records efficiently.'
  },
  {
    id: 9,
    category: 'personal',
    image: '/assets/td1.webp',
    images: [
      '/assets/td1.webp',
      '/assets/td2.webp',
      '/assets/td3.webp',
      '/assets/td4.webp',
      '/assets/td5.webp',
    ],
    title: 'TODUM',
    technologies: ['Angular', 'TypeScript', 'Java', 'Spring Boot'],
    simpleDescription: 'A task management application with authentication and productivity features.',
    description: 'Created with Angular for the frontend and Spring Boot for the backend, this application features user authentication, task categorization, priority settings, and deadline reminders. The intuitive interface and robust functionality make it easy for users to manage their daily activities and improve productivity.',
    githubUrl: 'https://github.com/AlonsoJIC/TodumFront'
  },
  {
    id: 10,
    category: 'personal',
    image: '/assets/lb0.webp',
    images: [
      '/assets/lb0.webp',
      '/assets/lb1.webp',
      '/assets/lb2.webp',
      '/assets/lb3.webp',
      '/assets/lbdb.webp',
    ],
    title: 'Not Found 404 Library',
    technologies: ['Visual Studio 2022', 'C#', '.NET', 'SQL Server', 'ADO.NET'],
    simpleDescription: 'A desktop application for managing a library system with CRUD operations.',
    description: 'A desktop application for managing a library system. The application allows users to perform CRUD operations on books, authors, and users. It features a user-friendly interface built with Windows Forms and utilizes ADO.NET for database connectivity with SQL Server. Implemented search functionality to quickly locate books and authors within the library database.'
  },
  {
    id: 11,
    category: 'professional-client',
    image: '/assets/gpr1.webp',
    images: [
      '/assets/gpr1.webp',
      '/assets/gpr2.webp',
      '/assets/gpr3.webp',
    ],
    title: 'Godo Painting - Rework',
    technologies: ['WordPress'],
    simpleDescription: 'Complete redesign of Godo Painting website with improved UX and SEO.',
    description: 'Godo Painting is a company that provides painting services in Tampa, FL. In this project, I made a complete redesign of the website to improve the user experience and SEO positioning.'
  },
  {
    id: 12,
    category: 'professional-client',
    image: '/assets/qg1.webp',
    images: [
      '/assets/qg1.webp',
    ],
    title: 'Quantum Games',
    technologies: ['Angular', 'TypeScript', 'HTML', 'SCSS'],
    simpleDescription: 'A gaming company website with an admin panel for content management.',
    description: 'Quantum Games is a web application created for a friend who wants to start a gaming company. This web was created with Angular, TypeScript, HTML, and SCSS. JWT authentication was implemented for the admin panel, where he can manage the games and the content of the website.'
  },
  {
    id: 13,
    category: 'professional-client',
    image: '/assets/ja1.webp',
    images: [
      '/assets/ja1.webp',
      '/assets/ja2.webp',
      '/assets/ja3.webp',
    ],
    title: 'Joyarte',
    technologies: ['Angular', 'TypeScript', 'HTML', 'SCSS'],
    simpleDescription: 'A modern website for a local art gallery showcasing artworks and exhibitions.',
    description: 'Joyarte is a website created for a local art gallery in my city. This web was created with Angular, TypeScript, HTML, and SCSS, featuring a clean design to showcase artworks.',
    githubUrl: 'https://github.com/AlonsoJIC/JoyarteWeb'
  },
  {
    id: 14,
    category: 'personal',
    image: '/assets/guess.webp',
    images: [
      '/assets/guess.webp',
    ],
    title: 'React Learning Projects',
    technologies: ['React', 'JavaScript'],
    simpleDescription: 'A collection of projects built while learning React and its ecosystem.',
    description: 'Currently learning about how to use React and its libraries. This project includes various exercises and small applications to practice React concepts like hooks, state management, and component architecture.'
  },
  {
    id: 17,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Tolaria - Trading Card Marketplace',
    technologies: ['WordPress', 'WooCommerce', 'PHP', 'JavaScript', 'Divi'],
    simpleDescription: 'Multi-vendor marketplace for Magic: The Gathering and Pokemon trading cards.',
    description: 'I owned the delivery of Tolaria from an empty theme to an operational e-commerce platform. I structured the site with Divi, built category and attribute-based product discovery, created reusable product layouts, and implemented seller and administrator workflows, product moderation, registration, and login with custom PHP. I also integrated the Onvopay payment gateway, developed an AJAX cart, and optimized key graphics by moving them to SVG.',
    liveUrl: 'https://tolariacr.com/',
    clientName: 'Tolaria'
  },
  {
    id: 18,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Lago & Sarmiento - Corporate Website',
    technologies: ['WordPress', 'ACF', 'PHP', 'Divi'],
    simpleDescription: 'Self-manageable corporate website with structured content architecture.',
    description: 'I led the end-to-end build of Lago & Sarmiento, translating the brand manual into a structured WordPress platform. I created custom post types and Advanced Custom Fields for courses, news, workshops, and resources, allowing the client to manage content independently. I also developed a custom events carousel and implemented the site visual identity, contact channels, maps, and institutional pages.',
    clientName: 'Lago & Sarmiento'
  },
  {
    id: 19,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Camara de Industrias de Costa Rica - Data Migration',
    technologies: ['Web Scraping', 'WordPress', 'CSV', 'Divi'],
    simpleDescription: 'Automated migration of 707 association member records and large-scale content publishing.',
    description: 'I replaced a planned manual data-entry process with an extraction pipeline that scraped the source data, generated a clean CSV, and bulk-imported 707 association records. I also published and formatted 550 forum posts with WebP-optimized imagery, reducing repetitive work and the risk of transcription errors.',
    clientName: 'Camara de Industrias de Costa Rica'
  },
  {
    id: 20,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Salud en Linea - E-commerce Maintenance',
    technologies: ['WordPress', 'WooCommerce', 'Divi'],
    simpleDescription: 'Content, product catalog, theme-template fixes, and platform maintenance for an online store.',
    description: 'I worked across editorial content, catalog architecture, and platform reliability for Salud en Linea. I rebuilt the product taxonomy, republished the inventory, fixed a Divi Theme Builder conflict, and completed backups, WordPress and plugin updates, dependency-conflict resolution, and security hardening.',
    liveUrl: 'https://saludenlineacr.shop/',
    clientName: 'Salud en Linea'
  },
  {
    id: 21,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Simtec Equipo Medico - Functional Improvements',
    technologies: ['JavaScript', 'jQuery', 'WordPress', 'Divi'],
    simpleDescription: 'Custom contact-routing and navigation improvements for a medical equipment website.',
    description: 'I built a custom JavaScript and jQuery solution that split sales and technical-support inquiries through the existing contact widget, avoiding a paid plugin upgrade. I also replaced a broken Waze redirect with a Google Maps integration that opens the visitor navigation app, and standardized typography and imagery across the site.',
    liveUrl: 'https://simteccr.com/',
    clientName: 'Simtec Equipo Medico'
  },
  {
    id: 22,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Escojisa CR - Site Redesign',
    technologies: ['WordPress', 'CSS', 'HTML', 'Divi'],
    simpleDescription: 'Responsive redesign and visual standardization based on iterative client reviews.',
    description: 'I drove a multi-round redesign of Escojisa CR, improving typography, color contrast, responsive layouts, footer structure, buttons, social integrations, and project imagery. I also migrated key icons to SVG and translated live client feedback into shipped visual and content updates.',
    liveUrl: 'https://escojisacr.com/',
    clientName: 'Escojisa CR'
  },
  {
    id: 23,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Fundacion Piedad - Institutional Website',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Institutional website foundation for a nonprofit organization.',
    description: 'I led the first build phase of the foundation website, using the client brief and competitive analysis to create the organization presentation, history, and affiliated-schools sections.',
    clientName: 'Fundacion Piedad'
  },
  {
    id: 24,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'SIBOWAK - Institutional Website',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Foundational architecture and global design system for an institutional website.',
    description: 'I built the foundational architecture for SIBOWAK across six business areas: organization, wellness, culture, home, products, and business. I also established the base template and global Divi style system used by later build phases.',
    liveUrl: 'https://sibowak.cr/',
    clientName: 'SIBOWAK'
  },
  {
    id: 25,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Esfera Latam - UX and Visual Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Homepage redesign focused on content flow, calls to action, and visual consistency.',
    description: 'I led an ongoing UX and visual redesign of Esfera Latam\'s homepage, restructuring content for readability, adding calls to action, standardizing information cards, and aligning the palette, typography, and graphic components with the brand guidelines.',
    liveUrl: 'https://esferalatam.com/',
    clientName: 'Esfera Latam'
  },
  {
    id: 26,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Girasol Gatuno - Visual Identity Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Responsive visual refresh with updated typography, imagery, navigation, and graphic components.',
    description: 'I led a visual identity refresh for Girasol Gatuno, reworking global typography, imagery, buttons, navigation links, CSS effects, and graphic components. I finished with responsive QA across mobile and desktop layouts.',
    liveUrl: 'https://girasolgatuno.com/',
    clientName: 'Girasol Gatuno'
  },
  {
    id: 27,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Ecole Travel - Content and Site Maintenance',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Ongoing blog and homepage maintenance with responsive content improvements.',
    description: 'I managed content and design updates for Ecole Travel, including author attribution, Instagram integration, homepage hero copy and imagery, and logo upscaling for sharper high-density display. I verified the changes through responsive QA.',
    liveUrl: 'https://ecoletravel.com/',
    clientName: 'Ecole Travel'
  },
  {
    id: 28,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'El Maestro en Casa - Academic Content Architecture',
    technologies: ['WordPress', 'Divi'],
    simpleDescription: 'Academic content audit and structure redesign for a distance-learning platform.',
    description: 'I audited and reorganized academic content, removed duplicated shared materials, designed a new structure for the 11th-grade Biology curriculum, and identified resource gaps for follow-up planning.',
    clientName: 'El Maestro en Casa'
  },
  {
    id: 29,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'MundoGluck - About Us Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Responsive redesign of an About Us section through two rounds of client feedback.',
    description: 'I replaced an outdated carousel layout with a cleaner responsive template, refined copy and visual hierarchy through client feedback, and improved spacing, alignment, and social-media placement.',
    liveUrl: 'https://mundogluck.com/',
    clientName: 'MundoGluck'
  },
  {
    id: 30,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Esteban Bogantes - Content and Visual Redesign',
    technologies: ['WordPress', 'CSS', 'Divi'],
    simpleDescription: 'Informational-page redesign with updated content, imagery, and visual consistency.',
    description: 'I redesigned a key informational page by replacing imagery, rewriting headings and subheadings within the defined color palette, and adjusting graphic elements to match the rest of the site.',
    liveUrl: 'https://estebanbogantes.com/',
    clientName: 'Esteban Bogantes'
  },
  {
    id: 31,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'VV Phoenix Ops',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Full corporate website for a project management staffing and delivery support company.',
    description: 'I built the complete corporate website for VV Phoenix Ops, creating a conversion-focused brand narrative around project staffing, PMO support, implementation leadership, and nearshore operations. The site includes service positioning, trust-building sections, contact flow, and a clean structure designed to communicate expertise and drive qualified consultations.',
    liveUrl: 'https://vvphoenixops.com/',
    clientName: 'VV Phoenix Ops'
  },
  {
    id: 32,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Estrategika',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Full business consulting website focused on management, growth, and operational structure.',
    description: 'I designed and developed the complete website for Estrategika, translating the consulting model into a clear and persuasive digital presence. The project covers the company positioning, service offer, methodology, credibility-building content, and calls to action aimed at business owners who need better governance, accountability, and execution.',
    clientName: 'Estrategika'
  },
  {
    id: 33,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'SM Consultora',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Strategic consulting website centered on public procurement readiness and business growth.',
    description: 'I created the full website for SM Consultora, building a strong narrative around planning, financial structure, organizational readiness, and public bidding strategy. The site consolidates the service offer, value proposition, corporate positioning, and contact experience to help companies compete with more clarity and strength.',
    clientName: 'SM Consultora'
  },
  {
    id: 34,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'SYSTEC',
    technologies: ['WordPress', 'CSS', 'JavaScript', 'IT Services'],
    simpleDescription: 'Complete digital presence for an IT infrastructure and cybersecurity company serving SMEs.',
    description: 'I developed the complete website for SYSTEC in close collaboration with the client to reflect their infrastructure, IT support, and cybersecurity services. The project included a full corporate presentation, service storytelling, credibility elements, and a communication structure designed for lead generation and trust-building with business clients.',
    liveUrl: 'https://systec.cr/',
    clientName: 'SYSTEC'
  },
  {
    id: 35,
    category: 'professional-client',
    image: '/assets/placeholder.svg',
    images: ['/assets/placeholder.svg'],
    title: 'Constructora DIA S.A.',
    technologies: ['WordPress', 'CSS', 'PHP', 'Divi'],
    simpleDescription: 'Project portfolio and institutional website for a construction company in Costa Rica.',
    description: 'I developed the projects section and supported the content architecture for Constructora DIA S.A., shaping a construction-focused portfolio that showcases residential, institutional, and commercial developments. The work included building a structured project showcase, improving information hierarchy, and creating a cleaner presentation for the company’s built work and credibility.',
    clientName: 'Constructora DIA S.A.'
  }

]
